spring:
  mail:
    host: smtp.gmail.com
    username: riqqa03@gmail.com
    password: amina@rokia
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
